import { getItem, setItem } from "./storageHelper.js";

const mealOptions = {
  "Lose Weight": {
    breakfast: [
      {
        name: "Oatmeal with fruit",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 250,
      },
      {
        name: "Egg white omelette with spinach",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 275,
      },
      {
        name: "Greek yogurt with berries",
        vegan: false,
        vegetarian: true,
        lactoseFree: false,
        glutenFree: true,
        calories: 300,
      },
    ],
    lunch: [
      {
        name: "Grilled chicken salad",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 300,
      },
      {
        name: "Quinoa salad with mixed vegetables",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 325,
      },
      {
        name: "Tuna salad with avocado",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 350,
      },
    ],
    dinner: [
      {
        name: "Grilled salmon with steamed vegetables",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 350,
      },
      {
        name: "Turkey breast with roasted sweet potatoes",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 375,
      },
      {
        name: "Baked tofu with stir-fried vegetables",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 400,
      },
    ],
  },
  "Gain Muscle": {
    breakfast: [
      {
        name: "Whole grain toast with peanut butter",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 550,
      },
      {
        name: "Scrambled eggs with whole wheat toast",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 575,
      },
      {
        name: "Protein smoothie with banana and spinach",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 600,
      },
    ],
    lunch: [
      {
        name: "Grilled chicken breast with brown rice",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 650,
      },
      {
        name: "Beef stir-fry with vegetables",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 675,
      },
      {
        name: "Quinoa and black bean bowl",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 700,
      },
    ],
    dinner: [
      {
        name: "Baked salmon with quinoa",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 700,
      },
      {
        name: "Lean beef with sweet potato mash",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 725,
      },
      {
        name: "Chicken and vegetable skewers",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 750,
      },
      {
        name: "Vegan protein bowl",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 775,
      },
    ],
  },
  "Improve Fitness": {
    breakfast: [
      {
        name: "Whole grain cereal with low-fat milk",
        vegan: false,
        vegetarian: true,
        lactoseFree: false,
        glutenFree: true,
        calories: 400,
      },
      {
        name: "Fruit smoothie with protein powder",
        vegan: true,
        vegetarian: true,
        lactoseFree: false,
        glutenFree: true,
        calories: 425,
      },
      {
        name: "Avocado toast with poached egg",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 450,
      },
    ],
    lunch: [
      {
        name: "Turkey wrap with vegetables",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 475,
      },
      {
        name: "Brown rice bowl with grilled tofu",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 500,
      },
      {
        name: "Whole wheat pasta with marinara sauce",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 525,
      },
    ],
    dinner: [
      {
        name: "Grilled shrimp with quinoa salad",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 525,
      },
      {
        name: "Vegetable stir-fry with tofu",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 550,
      },
      {
        name: "Whole wheat pizza with vegetables",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 575,
      },
    ],
  },
  "Maintain Weight": {
    breakfast: [
      {
        name: "Whole wheat pancakes with berries",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 450,
      },
      {
        name: "Yogurt parfait with granola",
        vegan: false,
        vegetarian: true,
        lactoseFree: false,
        glutenFree: true,
        calories: 475,
      },
      {
        name: "Egg and vegetable scramble",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 500,
      },
    ],
    lunch: [
      {
        name: "Quinoa salad with grilled chicken",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 525,
      },
      {
        name: "Vegetable soup with whole grain bread",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 550,
      },
      {
        name: "Grilled cheese sandwich with tomato soup",
        vegan: false,
        vegetarian: true,
        lactoseFree: false,
        glutenFree: false,
        calories: 575,
      },
    ],
    dinner: [
      {
        name: "Grilled fish with roasted vegetables",
        vegan: false,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 575,
      },
      {
        name: "Pasta primavera with whole wheat noodles",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: false,
        calories: 600,
      },
      {
        name: "Bean burrito bowl",
        vegan: true,
        vegetarian: true,
        lactoseFree: true,
        glutenFree: true,
        calories: 625,
      },
    ],
  },
};

// Script to Add data to local storage if not present
const addDataToLocalStorage = () => {
  if (getItem("mealOptions") === null) {
    setItem("mealOptions", mealOptions);
  }
};

export default addDataToLocalStorage;
